name: PHPUnit Tests

on:
  push:
    branches:
      - main
      - lignefacture
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: devops_db
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, intl, sqlite3, mysqli
        ini-values: |
          memory_limit=-1
        coverage: none

    - name: Install dependencies
      run: composer install --no-progress --no-suggest

    - name: Wait for MySQL to be ready
      run: sleep 20

    - name: Run migrations
      run: php spark migrate

    - name: Run PHPUnit
      run: vendor/bin/phpunit
